sudo: false
cache:
  directories:
    - $HOME/.stack
apt:
  packages:
    - ruby
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup
  - make build-dependencies
install:
  - stack --no-terminal install --only-dependencies
script:
  - make check
