build: off

cache:
  - '%LOCALAPPDATA%\Programs\stack'

before_build:
  - curl -o stack.zip -L --insecure https://www.stackage.org/stack/windows-x86_64
  - 7z x stack.zip stack.exe
  - stack --no-terminal setup > nul

build_script:
  - stack --no-terminal build
  - stack --no-terminal install --local-bin-path=out\build

test_script:
  - '.\out\build\smoke-exe --command=.\out\build\smoke-exe test'
