cache:
  - '%LOCALAPPDATA%\Programs\stack -> stack.yaml'
  - '%APPDATA%\stack -> stack.yaml'
  - ".stack-work -> stack.yaml, package.yaml"

build: off

before_build:
  - "choco install --yes --no-progress haskell-stack"
  - "stack --no-terminal setup"

build_script:
  - ps: 'New-Item -ItemType Directory -Path .\out\build\release,.\out\publish'
  - "stack --no-terminal build"
  - 'stack --no-terminal install --local-bin-path=.\out\build\release'
  - ps: 'Copy-Item .\out\build\release\smoke.exe .\out\publish\smoke-${env:APPVEYOR_REPO_TAG_NAME}-windows-x64.exe'

test_script:
  - "stack --no-terminal test"
  - ps: '.\out\build\release\smoke.exe --command=.\out\build\release\smoke.exe spec'

artifacts:
  - name: published
    path: 'out\publish\smoke-$(APPVEYOR_REPO_TAG_NAME)-windows-x64.exe'

deploy:
  provider: GitHub
  draft: true
  description: "Smoke $(APPVEYOR_REPO_TAG_NAME)"
  artifact: 'out\publish\smoke-$(APPVEYOR_REPO_TAG_NAME)-windows-x64.exe'
  force_update: true
  auth_token:
    secure: "QfL5WkDKhP5KNpeXpEgYGzLz65B7/hcVuhwwyRFul/rGEKYszbAVQ/vmFWtWVVcX"
  on:
    APPVEYOR_REPO_TAG: true
