name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-unix:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo 'This is a test on ${{ matrix.os }}.'
