name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}
          draft: true
      - run: echo "${{ steps.create_release.outputs.upload_url }}" > release_upload_url.txt
      - uses: actions/upload-artifact@v1
        with:
          name: release_upload_url
          path: release_upload_url.txt

  publish-unix:
    name: Release
    needs: release
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: samirtalwar
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-instantiate shell.nix | cachix push samirtalwar
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.stack
      #     key: v1-${{ matrix.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      - run: |
          mkdir -p ~/.stack
          cat > ~/.stack/config.yaml <<EOF
          nix:
            enable: true
          EOF
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make smoke.cabal'
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make out/build/release/smoke'
      - uses: actions/download-artifact@v1
        with:
          name: release_upload_url
      - id: release
        run: |
          echo ::set-output name=upload_url::"$(cat release_upload_url/release_upload_url.txt)"
      - id: asset
        run: |
          export TAG="${{ github.ref }}"
          export ASSET_NAME="smoke-${TAG##*/}-$(uname -s)-$(uname -m)"
          echo ::set-output name=asset_name::"$ASSET_NAME"
          echo ::set-output name=asset_path::"out/publish/${ASSET_NAME}"
      - run: |
          mkdir -p "$(dirname ${{ steps.asset.outputs.asset_path }})"
          cp out/build/release/smoke ${{ steps.asset.outputs.asset_path }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: ${{ steps.asset.outputs.asset_name }}
          asset_path: ${{ steps.asset.outputs.asset_path }}
          asset_content_type: application/octet-stream
