name: Verify
on:
  - push

jobs:
  verify-unix:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - run: nix-shell --pure --keep LANG --run true
      - run: nix-shell --pure --keep LANG --run 'cabal v2-update'
      - run: nix-shell --pure --keep LANG --run 'make test'
      - run: nix-shell --pure --keep LANG --run 'make lint'
