name: Verify
on:
  pull_request:
  push:

jobs:
  build-unix:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.3"
          enable-stack: true
          stack-no-global: true
      - uses: actions/cache@v2
        with:
          path: ~/.stack/snapshots
          key: v1-${{ matrix.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      - run: make smoke.cabal
      - run: make build

  test-unix:
    name: Build and Test
    needs: build-unix
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.3"
          enable-stack: true
          stack-no-global: true
      - uses: actions/cache@v2
        with:
          path: ~/.stack/snapshots
          key: v1-${{ matrix.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      - run: make smoke.cabal
      - run: make test

  lint:
    name: Lint
    needs: build-unix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: samirtalwar
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make lint'
