name: Verify
on:
  - push

jobs:
  install-dependencies-unix:
    name: Install dependencies
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: samirtalwar
          skipNixBuild: true
      - run: nix-instantiate shell.nix | cachix push samirtalwar
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-shell --pure --keep LANG --run 'cabal v2-update'

  test-linux:
    name: Build and test
    needs: install-dependencies-unix
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: samirtalwar
          skipNixBuild: true
      - uses: actions/cache@v1
        with:
          path: ~/.cabal/store
          key: v1-cabal-store-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: v1-cabal-store-
      - run: nix-shell --pure --keep LANG --run 'cabal v2-update'
      - run: nix-shell --pure --keep LANG --run 'make test'

  lint:
    name: Lint
    needs: install-dependencies-unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: samirtalwar
          skipNixBuild: true
      - run: nix-shell --pure --keep LANG --run 'make lint'
