name: Verify
on:
  pull_request:
  push:

jobs:
  build-unix:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: samirtalwar
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: |
          if [[ -n "$CACHIX_SIGNING_KEY" ]]; then
            nix-instantiate shell.nix | cachix push samirtalwar
          else
            nix-instantiate shell.nix
          fi
        env:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.stack
      #     key: v1-${{ matrix.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      - run: |
          mkdir -p ~/.stack
          cat > ~/.stack/config.yaml <<EOF
          nix:
            enable: true
          EOF
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make smoke.cabal'
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make build'

  test-unix:
    name: Build and Test
    needs: build-unix
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: samirtalwar
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.stack
      #     key: v1-${{ matrix.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      - run: |
          mkdir -p ~/.stack
          cat > ~/.stack/config.yaml <<EOF
          nix:
            enable: true
          EOF
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make smoke.cabal'
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make test'

  lint:
    name: Lint
    needs: build-unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: samirtalwar
      - run: nix-shell --pure --keep LANG ./nix/ci.nix --run 'make lint'
